### ISSUE TITLE
Can't download module

### ISSUE THREAD

**Issue by raph-m** [jonbodner/gcon#1]
Hello,

I know it's in pre-release, but I wanted to try this out and I can't download the package...

```bash
> go version
go version go1.18.3 darwin/amd64

> go get github.com/jonbodner/gcon@latest
go: github.com/jonbodner/gcon@v0.1.1: parsing go.mod:
	module declares its path as: gcon
	        but was required as: github.com/jonbodner/gcon
```
I think it's because your `go.mod` should declare your module with the full github path? Like this for example: https://github.com/opentracing/opentracing-go/blob/master/go.mod

I'd love to try this out, there's many places in our codebase where this would be useful :)

**Comment by jonbodner** [comment]
Oh, how embarrassing 😳 

Thanks for letting me know. I’ll get an updated version of go.mod up soon.

**Comment by jonbodner** [comment]
@raph-m The module path should now be correct. Please validate that it works and I’ll close the issue.

**Comment by raph-m** [comment]
Okay, I was able to test this on some of our code.
It's working great!
Thanks for the super-fast response.
We are looking into integrating this into our backend.
